@php($editing = isset($criterion))
<div class="grid gap-5 lg:grid-cols-2">
    <div><x-input-label for="code" value="Código" /><x-text-input id="code" name="code" class="mt-1 block w-full" :value="old('code', $criterion->code ?? '')" required /><x-input-error class="mt-2" :messages="$errors->get('code')" /></div>
    <div><x-input-label for="name" value="Nome" /><x-text-input id="name" name="name" class="mt-1 block w-full" :value="old('name', $criterion->name ?? '')" required /></div>
    <div><x-input-label for="category" value="Categoria" /><select id="category" name="category" class="mt-1 block w-full rounded-md border-ink-200">@foreach($categories as $value => $label)<option value="{{ $value }}" @selected(old('category', isset($criterion) ? $criterion->category->value : '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="target" value="Alvo" /><select id="target" name="target" class="mt-1 block w-full rounded-md border-ink-200">@foreach($targets as $value => $label)<option value="{{ $value }}" @selected(old('target', $criterion->target ?? '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="operator" value="Operador" /><select id="operator" name="operator" class="mt-1 block w-full rounded-md border-ink-200">@foreach($operators as $value => $label)<option value="{{ $value }}" @selected(old('operator', isset($criterion) ? $criterion->operator->value : '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="expected_value" value="Valor esperado (valor ou JSON)" /><x-text-input id="expected_value" name="expected_value" class="mt-1 block w-full" :value="old('expected_value', isset($criterion) && $criterion->expected_value ? json_encode($criterion->expected_value, JSON_UNESCAPED_UNICODE) : '')" /></div>
    <div><x-input-label for="minimum_value" value="Valor mínimo" /><x-text-input id="minimum_value" type="number" step="0.01" name="minimum_value" class="mt-1 block w-full" :value="old('minimum_value', $criterion->minimum_value ?? '')" /></div>
    <div><x-input-label for="maximum_value" value="Valor máximo" /><x-text-input id="maximum_value" type="number" step="0.01" name="maximum_value" class="mt-1 block w-full" :value="old('maximum_value', $criterion->maximum_value ?? '')" /><x-input-error class="mt-2" :messages="$errors->get('maximum_value')" /></div>
    <div><x-input-label for="unit" value="Unidade" /><x-text-input id="unit" name="unit" class="mt-1 block w-full" :value="old('unit', $criterion->unit ?? '')" /></div>
    <div><x-input-label for="sort_order" value="Ordem" /><x-text-input id="sort_order" type="number" min="0" name="sort_order" class="mt-1 block w-full" :value="old('sort_order', $criterion->sort_order ?? 0)" /></div>
    <div class="lg:col-span-2"><x-input-label for="description" value="Descrição técnica" /><textarea id="description" name="description" rows="3" class="mt-1 block w-full rounded-md border-ink-200">{{ old('description', $criterion->description ?? '') }}</textarea></div>
    <div><x-input-label for="success_message" value="Mensagem de sucesso" /><textarea id="success_message" name="success_message" rows="3" class="mt-1 block w-full rounded-md border-ink-200">{{ old('success_message', $criterion->success_message ?? '') }}</textarea></div>
    <div><x-input-label for="failure_message" value="Mensagem de falha" /><textarea id="failure_message" name="failure_message" rows="3" class="mt-1 block w-full rounded-md border-ink-200">{{ old('failure_message', $criterion->failure_message ?? '') }}</textarea></div>
    <div class="lg:col-span-2"><x-input-label for="review_message" value="Mensagem de análise manual" /><textarea id="review_message" name="review_message" rows="3" class="mt-1 block w-full rounded-md border-ink-200">{{ old('review_message', $criterion->review_message ?? '') }}</textarea></div>
    <label class="flex items-center gap-3 text-sm"><input type="checkbox" name="is_mandatory" value="1" class="rounded" @checked(old('is_mandatory', $criterion->is_mandatory ?? true))>Critério obrigatório</label>
    <label class="flex items-center gap-3 text-sm"><input type="checkbox" name="requires_manual_review" value="1" class="rounded" @checked(old('requires_manual_review', $criterion->requires_manual_review ?? false))>Requer análise manual</label>
    <label class="flex items-center gap-3 text-sm"><input type="checkbox" name="is_active" value="1" class="rounded" @checked(old('is_active', $criterion->is_active ?? true))>Critério ativo</label>
</div>
<div class="mt-6 flex gap-3"><button class="mv-button-primary">{{ $editing ? 'Guardar alterações' : 'Criar critério' }}</button><a href="{{ route('backoffice.eligibility.criteria.index', $ruleSet) }}" class="mv-button-secondary">Cancelar</a></div>
