<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-civic-700">Reclamação</p><h1 class="mt-1 text-2xl font-semibold text-ink-900">{{ $complaint->complaint_number }}</h1></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-5xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="rounded-md border border-ink-100 bg-white p-6"><dl class="grid gap-4 md:grid-cols-3 text-sm"><div><dt class="text-ink-500">Candidato</dt><dd>{{ $complaint->candidate?->name }}</dd></div><div><dt class="text-ink-500">Estado</dt><dd>{{ $complaint->status->label() }}</dd></div><div><dt class="text-ink-500">Lista</dt><dd>{{ $complaint->provisionalList?->list_number }}</dd></div></dl><h2 class="mt-6 font-semibold">{{ $complaint->subject }}</h2><p class="mt-2 whitespace-pre-line text-sm text-ink-700">{{ $complaint->grounds }}</p></div>
        <div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('backoffice.complaints.mark-received', $complaint) }}">@csrf<x-secondary-button>Marcar recebida</x-secondary-button></form><form method="POST" action="{{ route('backoffice.complaints.start-review', $complaint) }}">@csrf<x-secondary-button>Iniciar análise</x-secondary-button></form><a href="{{ route('backoffice.complaint-decisions.create', $complaint) }}" class="rounded-md bg-civic-700 px-4 py-2 text-sm font-semibold text-white">Criar decisão</a><a href="{{ route('backoffice.additional-information-requests.create', $complaint) }}" class="rounded-md border border-ink-200 px-4 py-2 text-sm font-semibold">Pedir informação</a></div>
        <form method="POST" action="{{ route('backoffice.complaints.assign', $complaint) }}" class="rounded-md border border-ink-100 bg-white p-4">@csrf<x-input-label for="assigned_to" value="Técnico responsável" /><div class="mt-2 flex gap-2"><select id="assigned_to" name="assigned_to" class="w-full rounded-md border-ink-200">@foreach($technicians as $technician)<option value="{{ $technician->id }}">{{ $technician->name }}</option>@endforeach</select><x-secondary-button>Atribuir</x-secondary-button></div></form>
        @if($complaint->decision)<div class="rounded-md border border-ink-100 bg-white p-6"><h2 class="font-semibold">Decisão</h2><p class="mt-2 text-sm">{{ $complaint->decision->summary }}</p><a class="mt-3 inline-block font-semibold text-civic-700" href="{{ route('backoffice.complaint-decisions.show', $complaint->decision) }}">Abrir decisão</a></div>@endif
    </div></div>
</x-app-layout>

