<x-app-layout>
    <x-slot name="header"><h1 class="text-xl font-semibold text-ink-900">{{ $propertyInspection->inspection_number }}</h1></x-slot>
    <div class="space-y-6">
        <div class="mv-card grid gap-3 md:grid-cols-4"><div><p class="text-xs text-ink-500">Tipo</p><p class="font-semibold">{{ $propertyInspection->inspection_type->label() }}</p></div><div><p class="text-xs text-ink-500">Estado</p><p class="font-semibold">{{ $propertyInspection->status->label() }}</p></div><div><p class="text-xs text-ink-500">Habitação</p><p class="font-semibold">{{ $propertyInspection->housingUnit?->code }}</p></div><div><p class="text-xs text-ink-500">Condição</p><p class="font-semibold">{{ $propertyInspection->general_condition?->label() ?? '-' }}</p></div></div>
        <div class="mv-card"><p>{{ $propertyInspection->summary }}</p><p class="text-sm text-ink-500">{{ $propertyInspection->recommendations }}</p></div>
        <form method="POST" action="{{ route('backoffice.inspections.complete', $propertyInspection) }}" class="mv-card grid gap-3">@csrf<select class="mv-input" name="general_condition"><option value="good">Boa</option><option value="acceptable">Aceitável</option><option value="requires_repair">Requer reparação</option><option value="poor">Má</option><option value="critical">Crítica</option></select><textarea class="mv-input" name="summary" placeholder="Resumo da vistoria" required></textarea><textarea class="mv-input" name="recommendations" placeholder="Recomendações"></textarea><button class="mv-button-secondary">Concluir vistoria</button></form>
        <div class="flex flex-wrap gap-3"><form method="POST" action="{{ route('backoffice.inspections.validate', $propertyInspection) }}">@csrf<button class="mv-button-secondary">Validar</button></form><form method="POST" action="{{ route('backoffice.inspections.reports.generate', $propertyInspection) }}">@csrf<button class="mv-button-primary">Gerar auto</button></form></div>
        <div class="mv-card"><h2 class="font-semibold">Checklist</h2>@foreach ($propertyInspection->items as $item)<p class="mt-2 text-sm">{{ $item->label }} · {{ $item->condition?->label() ?? 'Sem avaliação' }}</p>@endforeach</div>
    </div>
</x-app-layout>
