@php($item = $typologyAdequacyRule)
<div class="grid gap-4 md:grid-cols-2">
    <label class="text-sm font-medium text-ink-700 md:col-span-2">Nome<input name="name" value="{{ old('name', $item?->name) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Programa<select name="program_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Selecione</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((string) old('program_id', $item?->program_id) === (string) $program->id)>{{ $program->name }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Concurso<select name="contest_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Selecione</option>@foreach($contests as $contest)<option value="{{ $contest->id }}" @selected((string) old('contest_id', $item?->contest_id) === (string) $contest->id)>{{ $contest->title }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Mín. elementos<input type="number" name="min_household_members" value="{{ old('min_household_members', $item?->min_household_members) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Máx. elementos<input type="number" name="max_household_members" value="{{ old('max_household_members', $item?->max_household_members) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Mín. quartos<input type="number" name="min_bedrooms" value="{{ old('min_bedrooms', $item?->min_bedrooms) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Máx. quartos<input type="number" name="max_bedrooms" value="{{ old('max_bedrooms', $item?->max_bedrooms) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Tipologia<input name="typology" value="{{ old('typology', $item?->typology) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Prioridade<input type="number" name="priority_order" value="{{ old('priority_order', $item?->priority_order ?? 0) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="flex items-center gap-2 text-sm font-medium text-ink-700"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $item?->is_active ?? true))> Ativa</label>
    <label class="flex items-center gap-2 text-sm font-medium text-ink-700"><input type="hidden" name="requires_accessibility" value="0"><input type="checkbox" name="requires_accessibility" value="1" @checked(old('requires_accessibility', $item?->requires_accessibility))> Exige acessibilidade</label>
    <label class="text-sm font-medium text-ink-700 md:col-span-2">Descrição<textarea name="description" class="mt-1 w-full rounded-md border-ink-200">{{ old('description', $item?->description) }}</textarea></label>
</div>
