@php($editing = isset($contractTemplate))
<div class="grid gap-5 md:grid-cols-2">
    <div><x-input-label for="name" value="Nome" /><x-text-input id="name" name="name" class="mt-1 w-full" :value="old('name', $contractTemplate->name ?? '')" required /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 w-full rounded-md border-ink-200">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', isset($contractTemplate) ? $contractTemplate->status->value : 'draft') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="program_id" value="Programa" /><select id="program_id" name="program_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Selecionar</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((string) old('program_id', $contractTemplate->program_id ?? '') === (string) $program->id)>{{ $program->name }}</option>@endforeach</select></div>
    <div><x-input-label for="contest_id" value="Concurso" /><select id="contest_id" name="contest_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Aplicar ao programa</option>@foreach($contests as $contest)<option value="{{ $contest->id }}" @selected((string) old('contest_id', $contractTemplate->contest_id ?? '') === (string) $contest->id)>{{ $contest->title }}</option>@endforeach</select></div>
    <div><x-input-label for="version_number" value="Versão" /><x-text-input id="version_number" name="version_number" type="number" class="mt-1 w-full" :value="old('version_number', $contractTemplate->version_number ?? 1)" /></div>
    <div><x-input-label for="effective_from" value="Vigente desde" /><x-text-input id="effective_from" name="effective_from" type="date" class="mt-1 w-full" :value="old('effective_from', isset($contractTemplate) ? $contractTemplate->effective_from?->format('Y-m-d') : '')" /></div>
    <div class="md:col-span-2"><x-input-label for="template_body" value="Corpo da minuta" /><textarea id="template_body" name="template_body" rows="12" class="mt-1 w-full rounded-md border-ink-200" required>{{ old('template_body', $contractTemplate->template_body ?? "MINUTA DEMO - SUJEITA A VALIDACAO JURIDICA\n\nContrato {{contract.number}} entre {{municipality.name}} e {{tenant.name}}, referente à habitação {{housing.address}}, com início em {{contract.start_date}} e renda mensal de {{rent.amount}}.\n\n{{clauses}}\n\nCaução: {{deposit.amount}}.") }}</textarea><p class="mt-2 text-xs text-ink-500">Placeholders disponíveis: contract, tenant, housing, rent, deposit, program, contest, municipality e clauses.</p></div>
    <div class="md:col-span-2"><x-input-label value="Cláusulas" /><div class="mt-2 grid gap-2 md:grid-cols-2">@foreach($clauses as $clause)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="clause_ids[]" value="{{ $clause->id }}" @checked(collect(old('clause_ids', isset($contractTemplate) ? $contractTemplate->clauses->pluck('id')->all() : []))->contains($clause->id))>{{ $clause->code }} · {{ $clause->title }}</label>@endforeach</div></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Descrição" /><textarea id="description" name="description" rows="3" class="mt-1 w-full rounded-md border-ink-200">{{ old('description', $contractTemplate->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="mv-button-primary">{{ $editing ? 'Guardar' : 'Criar' }}</button><a href="{{ route('backoffice.contracts.templates.index') }}" class="mv-button-secondary">Cancelar</a></div>
