<x-app-layout>
    <x-slot name="header"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-sm font-semibold text-civic-700">Verificação #{{ $check->id }}</p><h1 class="mt-1 text-2xl font-semibold text-ink-900">{{ $check->result->label() }}</h1><p class="mt-1 text-sm text-ink-500">{{ $check->contest?->title ?? $check->program?->name ?? 'Sem regras aplicáveis' }}</p></div>@can('rerun', $check)<form method="POST" action="{{ route('backoffice.eligibility.checks.rerun', $check) }}">@csrf<button class="mv-button-secondary">Reexecutar</button></form>@endcan</div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8"><x-flash-message />
        <section class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div class="mv-surface p-5"><p class="text-sm text-ink-500">Tipo</p><p class="mt-2 font-semibold">{{ $check->check_type->label() }}</p></div><div class="mv-surface p-5"><p class="text-sm text-ink-500">Rule set</p><p class="mt-2 font-semibold">{{ $check->ruleSet?->name ?? 'Não aplicável' }}</p></div><div class="mv-surface p-5"><p class="text-sm text-ink-500">Executado por</p><p class="mt-2 font-semibold">{{ $check->executedBy?->name ?? 'Sistema' }}</p></div><div class="mv-surface p-5"><p class="text-sm text-ink-500">Data</p><p class="mt-2 font-semibold">{{ $check->executed_at?->format('d/m/Y H:i') }}</p></div></section>
        <section class="mv-surface p-6"><h2 class="font-semibold text-ink-900">Resumo</h2><p class="mt-2 text-sm leading-6 text-ink-600">{{ $check->summary }}</p>@if($check->missing_data)<p class="mt-4 text-xs font-semibold uppercase text-ink-500">Dados em falta</p><p class="mt-1 text-sm text-ink-600">{{ implode(', ', $check->missing_data) }}</p>@endif @if($check->warnings)<p class="mt-4 text-xs font-semibold uppercase text-ink-500">Alertas</p><ul class="mt-1 list-disc pl-5 text-sm text-ink-600">@foreach($check->warnings as $warning)<li>{{ $warning }}</li>@endforeach</ul>@endif</section>
        <section class="mv-surface overflow-hidden"><div class="border-b border-ink-100 px-6 py-4"><h2 class="font-semibold text-ink-900">Resultados por critério</h2></div><div class="overflow-x-auto"><table class="mv-table"><thead><tr><th>Critério</th><th>Resultado</th><th>Mensagem ao candidato</th><th>Detalhe técnico</th></tr></thead><tbody class="divide-y divide-ink-100">@forelse($check->results as $result)<tr><td><p class="font-semibold text-ink-900">{{ $result->name }}</p><p class="text-xs text-ink-500">{{ $result->code }}</p></td><td>{{ $result->result->label() }}</td><td>{{ $result->message }}</td><td class="max-w-md text-xs">{{ $result->technical_message }}</td></tr>@empty<tr><td colspan="4" class="text-center text-ink-500">Sem critérios aplicáveis.</td></tr>@endforelse</tbody></table></div></section>
        <section class="mv-surface p-6"><h2 class="font-semibold text-ink-900">Snapshots mínimos</h2><div class="mt-4 grid gap-3 lg:grid-cols-2">@foreach($check->snapshots as $snapshot)<details class="rounded-md border border-ink-100 p-4"><summary class="cursor-pointer text-sm font-semibold">{{ $snapshot->snapshot_type }}</summary><pre class="mt-3 max-h-72 overflow-auto whitespace-pre-wrap text-xs text-ink-600">{{ json_encode($snapshot->data, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE) }}</pre></details>@endforeach</div></section>
    </div></div>
</x-app-layout>
