@php($item = $allocationRuleSet)
<div class="grid gap-4 md:grid-cols-2">
    <label class="text-sm font-medium text-ink-700 md:col-span-2">Nome<input name="name" value="{{ old('name', $item?->name) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Programa<select name="program_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Selecione</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((string) old('program_id', $item?->program_id) === (string) $program->id)>{{ $program->name }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Concurso<select name="contest_id" class="mt-1 w-full rounded-md border-ink-200"><option value="">Selecione</option>@foreach($contests as $contest)<option value="{{ $contest->id }}" @selected((string) old('contest_id', $item?->contest_id) === (string) $contest->id)>{{ $contest->title }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Método<select name="allocation_method" class="mt-1 w-full rounded-md border-ink-200">@foreach($methods as $value => $label)<option value="{{ $value }}" @selected(old('allocation_method', $item?->allocation_method?->value) === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Estado<select name="status" class="mt-1 w-full rounded-md border-ink-200">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', $item?->status?->value ?? 'draft') === $value)>{{ $label }}</option>@endforeach</select></label>
    <label class="text-sm font-medium text-ink-700">Prazo de aceitação (dias)<input type="number" name="acceptance_deadline_days" value="{{ old('acceptance_deadline_days', $item?->acceptance_deadline_days ?? 10) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    <label class="text-sm font-medium text-ink-700">Máx. recusas<input type="number" name="max_refusals_allowed" value="{{ old('max_refusals_allowed', $item?->max_refusals_allowed ?? 1) }}" class="mt-1 w-full rounded-md border-ink-200"></label>
    @foreach(['allow_preferences' => 'Permite preferências', 'allow_lottery' => 'Permite sorteio', 'allow_manual_override' => 'Permite exceção manual', 'requires_acceptance' => 'Exige aceitação', 'auto_call_next_on_refusal' => 'Chamar suplente em recusa', 'auto_call_next_on_expiry' => 'Chamar suplente em expiração'] as $field => $label)
        <label class="flex items-center gap-2 text-sm font-medium text-ink-700"><input type="hidden" name="{{ $field }}" value="0"><input type="checkbox" name="{{ $field }}" value="1" @checked(old($field, $item?->{$field} ?? true))> {{ $label }}</label>
    @endforeach
    <label class="text-sm font-medium text-ink-700 md:col-span-2">Descrição<textarea name="description" class="mt-1 w-full rounded-md border-ink-200">{{ old('description', $item?->description) }}</textarea></label>
</div>
