@php($editing = isset($ruleSet))
<div class="grid gap-5 lg:grid-cols-2">
    <div><x-input-label for="name" value="Nome" /><x-text-input id="name" name="name" class="mt-1 w-full" :value="old('name', $ruleSet->name ?? '')" required /><x-input-error class="mt-2" :messages="$errors->get('name')" /></div>
    <div><x-input-label for="status" value="Estado" /><select id="status" name="status" class="mt-1 w-full rounded-2xl border-ink-200">@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected(old('status', isset($ruleSet) ? $ruleSet->status->value : 'draft') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="program_id" value="Programa" /><select id="program_id" name="program_id" class="mt-1 w-full rounded-2xl border-ink-200"><option value="">Selecionar</option>@foreach($programs as $program)<option value="{{ $program->id }}" @selected((string) old('program_id', $ruleSet->program_id ?? '') === (string) $program->id)>{{ $program->name }}</option>@endforeach</select><x-input-error class="mt-2" :messages="$errors->get('program_id')" /></div>
    <div><x-input-label for="contest_id" value="Concurso" /><select id="contest_id" name="contest_id" class="mt-1 w-full rounded-2xl border-ink-200"><option value="">Aplicar ao programa</option>@foreach($contests as $contest)<option value="{{ $contest->id }}" @selected((string) old('contest_id', $ruleSet->contest_id ?? '') === (string) $contest->id)>{{ $contest->title }}</option>@endforeach</select><x-input-error class="mt-2" :messages="$errors->get('contest_id')" /></div>
    <div><x-input-label for="calculation_method" value="Método" /><select id="calculation_method" name="calculation_method" class="mt-1 w-full rounded-2xl border-ink-200">@foreach($methods as $value => $label)<option value="{{ $value }}" @selected(old('calculation_method', isset($ruleSet) ? $ruleSet->calculation_method->value : 'effort_rate') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="income_basis" value="Base de rendimento" /><x-text-input id="income_basis" name="income_basis" class="mt-1 w-full" :value="old('income_basis', $ruleSet->income_basis ?? 'declared_income')" required /></div>
    <div><x-input-label for="income_period" value="Período de rendimento" /><x-text-input id="income_period" name="income_period" class="mt-1 w-full" :value="old('income_period', $ruleSet->income_period ?? 'monthly')" required /></div>
    <div><x-input-label for="effort_rate_percentage" value="Taxa de esforço (%)" /><x-text-input id="effort_rate_percentage" name="effort_rate_percentage" type="number" step="0.01" class="mt-1 w-full" :value="old('effort_rate_percentage', $ruleSet->effort_rate_percentage ?? '')" /></div>
    <div><x-input-label for="minimum_rent" value="Renda mínima" /><x-text-input id="minimum_rent" name="minimum_rent" type="number" step="0.01" class="mt-1 w-full" :value="old('minimum_rent', $ruleSet->minimum_rent ?? '')" /></div>
    <div><x-input-label for="maximum_rent" value="Renda máxima" /><x-text-input id="maximum_rent" name="maximum_rent" type="number" step="0.01" class="mt-1 w-full" :value="old('maximum_rent', $ruleSet->maximum_rent ?? '')" /></div>
    <div><x-input-label for="deposit_months" value="Meses de caução" /><x-text-input id="deposit_months" name="deposit_months" type="number" step="0.01" class="mt-1 w-full" :value="old('deposit_months', $ruleSet->deposit_months ?? '')" /></div>
    <div><x-input-label for="minimum_deposit" value="Caução mínima" /><x-text-input id="minimum_deposit" name="minimum_deposit" type="number" step="0.01" class="mt-1 w-full" :value="old('minimum_deposit', $ruleSet->minimum_deposit ?? '')" /></div>
    <div><x-input-label for="maximum_deposit" value="Caução máxima" /><x-text-input id="maximum_deposit" name="maximum_deposit" type="number" step="0.01" class="mt-1 w-full" :value="old('maximum_deposit', $ruleSet->maximum_deposit ?? '')" /></div>
    <div><x-input-label for="rounding_precision" value="Precisão de arredondamento" /><x-text-input id="rounding_precision" name="rounding_precision" type="number" class="mt-1 w-full" :value="old('rounding_precision', $ruleSet->rounding_precision ?? 2)" /></div>
    <div><x-input-label for="effective_from" value="Vigente desde" /><x-text-input id="effective_from" name="effective_from" type="date" class="mt-1 w-full" :value="old('effective_from', isset($ruleSet) ? $ruleSet->effective_from?->format('Y-m-d') : '')" /></div>
    <div><x-input-label for="effective_until" value="Vigente até" /><x-text-input id="effective_until" name="effective_until" type="date" class="mt-1 w-full" :value="old('effective_until', isset($ruleSet) ? $ruleSet->effective_until?->format('Y-m-d') : '')" /></div>
    <label class="flex items-center gap-3 text-sm text-ink-700"><input type="checkbox" name="requires_manual_approval" value="1" class="rounded border-ink-300 text-mvhab-primary" @checked(old('requires_manual_approval', $ruleSet->requires_manual_approval ?? true))> Exige aprovação manual</label>
    <label class="flex items-center gap-3 text-sm text-ink-700"><input type="checkbox" name="allow_manual_override" value="1" class="rounded border-ink-300 text-mvhab-primary" @checked(old('allow_manual_override', $ruleSet->allow_manual_override ?? true))> Permite revisão manual</label>
    <div class="lg:col-span-2"><x-input-label for="description" value="Descrição" /><textarea id="description" name="description" rows="3" class="mt-1 w-full rounded-2xl border-ink-200">{{ old('description', $ruleSet->description ?? '') }}</textarea></div>
</div>
<div class="mt-6 flex gap-3"><button class="mv-button-primary">{{ $editing ? 'Guardar' : 'Criar' }}</button><a href="{{ route('backoffice.contracts.rent-rule-sets.index') }}" class="mv-button-secondary">Cancelar</a></div>
