<?php

return [
    'e2e_user_password' => env('MVHAB_E2E_USER_PASSWORD'),
    'seed_state_of_art_demo' => env('MVHAB_SEED_STATE_OF_ART_DEMO', false),
    'regulatory_demo_mode' => env('MVHAB_REGULATORY_DEMO_MODE', false),

    // Limites técnicos conservadores; não representam prazos regulamentares.
    'rate_limits' => [
        'program53' => [
            'export_preview' => [
                'normal' => [
                    'user' => ['max_attempts' => 20, 'decay_seconds' => 60],
                    'municipality' => ['max_attempts' => 100, 'decay_seconds' => 60],
                ],
                'sensitive' => [
                    'user' => ['max_attempts' => 5, 'decay_seconds' => 60],
                    'municipality' => ['max_attempts' => 20, 'decay_seconds' => 60],
                ],
            ],
            'export_request' => [
                'normal' => [
                    'user' => ['max_attempts' => 5, 'decay_seconds' => 300],
                    'municipality' => ['max_attempts' => 25, 'decay_seconds' => 300],
                ],
                'sensitive' => [
                    'user' => ['max_attempts' => 2, 'decay_seconds' => 300],
                    'municipality' => ['max_attempts' => 8, 'decay_seconds' => 300],
                ],
            ],
            'export_download' => [
                'normal' => [
                    'user' => ['max_attempts' => 20, 'decay_seconds' => 60],
                    'municipality' => ['max_attempts' => 100, 'decay_seconds' => 60],
                ],
                'sensitive' => [
                    'user' => ['max_attempts' => 5, 'decay_seconds' => 60],
                    'municipality' => ['max_attempts' => 20, 'decay_seconds' => 60],
                ],
            ],
            'batch_seal' => [
                'normal' => [
                    'user' => ['max_attempts' => 5, 'decay_seconds' => 300],
                    'municipality' => ['max_attempts' => 20, 'decay_seconds' => 300],
                ],
            ],
            'batch_publish' => [
                'normal' => [
                    'user' => ['max_attempts' => 3, 'decay_seconds' => 300],
                    'municipality' => ['max_attempts' => 10, 'decay_seconds' => 300],
                ],
            ],
            'revalidation_seal' => [
                'normal' => [
                    'user' => ['max_attempts' => 5, 'decay_seconds' => 300],
                    'municipality' => ['max_attempts' => 20, 'decay_seconds' => 300],
                ],
            ],
        ],
    ],

    'municipal_application_demo' => [
        'enabled' => env(
            'MVHAB_MUNICIPAL_APPLICATION_DEMO',
            false,
        ),

        'reference_date' => env(
            'MVHAB_DEMO_REFERENCE_DATE',
        ),

        'user_password' => env(
            'MVHAB_DEMO_USER_PASSWORD',
        ),
    ],

    'permissions' => [
        'dashboard' => ['view', 'export', 'audit'],
        'users' => ['view', 'create', 'update', 'delete', 'deactivate', 'reactivate', 'force_mfa', 'reset_password', 'audit'],
        'roles' => ['view', 'create', 'update', 'delete', 'assign', 'remove', 'audit'],
        'teams' => ['view', 'create', 'update', 'manage_members', 'audit'],
        'access_audit' => ['view', 'export', 'audit'],
        'work_tasks' => ['view', 'view_team', 'create', 'assign', 'claim', 'reassign', 'update_status', 'complete', 'cancel', 'audit', 'dashboard', 'manage_sla'],
        'security' => [
            'view',
            'update',
            'resolve',
            'approve',
            'manage_own_mfa',
            'view_access_logs',
            'revoke_sessions',
            'audit_sensitive_access',
        ],
        'permission_reviews' => ['view', 'create', 'update', 'complete', 'audit'],
        'exports' => ['view', 'create', 'download', 'audit', 'delete', 'rgpd', 'sensitive.create', 'sensitive.download', 'sensitive.audit'],
        'rgpd' => [
            'retention.view',
            'retention.manage',
            'retention.approve',
            'retention.execute',
            'anonymization.view',
            'anonymization.request',
            'anonymization.approve',
            'anonymization.execute',
            'dpo.approve',
        ],
        'municipalities' => ['view', 'create', 'update', 'delete', 'audit'],
        'municipality_features' => ['view', 'update', 'audit'],
        'platform_operators' => ['view', 'manage', 'audit'],
        'programs' => ['view', 'create', 'update', 'delete', 'publish', 'audit'],
        'contests' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'publish', 'close', 'audit'],
        'citizens' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'adhesion_registrations' => ['view', 'create', 'update', 'approve', 'reject', 'export', 'audit'],
        'applications' => ['view', 'create', 'update', 'delete', 'submit', 'withdraw', 'approve', 'reject', 'export', 'audit'],
        'households' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'income_records' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'documents' => [
            'view',
            'create',
            'update',
            'replace',
            'delete',
            'download',
            'analyze',
            'review_ai',
            'generate',
            'activate',
            'archive',
            'preview',
            'issue',
            'cancel',
            'approve',
            'reject',
            'publish',
            'export',
            'audit',
        ],
        'eligibility' => [
            'view',
            'create',
            'update',
            'run',
            'activate',
            'deactivate',
            'archive',
            'duplicate',
            'approve',
            'reject',
            'export',
            'audit',
        ],
        'administrative_processes' => [
            'view',
            'create',
            'update',
            'delete',
            'assign',
            'decide',
            'complete',
            'cancel',
            'issue',
            'mark_overdue',
            'approve',
            'reject',
            'publish',
            'export',
            'audit',
        ],
        'administrative_decisions' => [
            'view',
            'create',
            'approve',
            'cancel',
        ],
        'scoring' => [
            'view',
            'create',
            'update',
            'review',
            'run',
            'lock',
            'cancel',
            'activate',
            'deactivate',
            'archive',
            'duplicate',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
        ],
        'public_lists' => [
            'view',
            'create',
            'update',
            'delete',
            'generate',
            'review',
            'approve',
            'reject',
            'publish',
            'archive',
            'cancel',
            'lock',
            'open_complaint_period',
            'close_complaint_period',
            'export',
            'audit',
        ],
        'hearings' => ['view', 'create', 'issue', 'review', 'accept', 'reject', 'close', 'cancel'],
        'complaints' => [
            'view',
            'create',
            'update',
            'delete',
            'assign',
            'mark_received',
            'review',
            'request_information',
            'mark_overdue',
            'close',
            'decide',
            'approve',
            'reject',
            'cancel',
            'export',
            'audit',
        ],
        'allocations' => ['view', 'create', 'update', 'approve', 'reject', 'process_withdrawal', 'export', 'audit'],
        'lotteries' => [
            'view',
            'create',
            'update',
            'run',
            'validate',
            'cancel',
            'export',
            'participants.load',
            'participants.lock',
            'convocations.generate',
            'convocations.send',
            'attendance.manage',
            'winners.register',
            'reports.generate',
        ],
        'contracts' => [
            'view',
            'create',
            'update',
            'delete',
            'issue',
            'activate',
            'suspend',
            'terminate',
            'cancel',
            'sign',
            'approve',
            'reject',
            'export',
            'audit',
            'templates.activate',
            'templates.archive',
            'templates.duplicate',
            'clauses.activate',
            'clauses.archive',
            'validations.create',
            'validations.approve',
            'validations.reject',
            'key_handovers.view',
            'key_handovers.schedule',
            'key_handovers.update',
            'key_handovers.complete',
            'key_handovers.cancel',
            'tenant_transitions.view',
            'tenant_transitions.run',
            'communications.view',
            'communications.create',
            'communications.message',
            'charge_runs.view',
            'charge_runs.run',
            'dashboard',
            'maintenance_reports.view',
        ],
        'payments' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'allocate',
            'confirm',
            'reverse',
            'imports.view',
            'imports.create',
            'imports.process',
            'receipts.view',
            'receipts.generate',
            'receipts.download',
            'receipts.cancel',
            'invoices.view',
            'invoices.generate',
            'tenant.view',
            'tenant.create',
            'tenant.confirm',
        ],
        'finance' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'deposits.view',
            'deposits.request',
            'deposits.mark_paid',
            'deposits.waive',
            'deposits.cancel',
            'rent_calculations.view',
            'rent_calculations.calculate',
            'rent_calculations.recalculate',
            'rent_calculations.approve',
            'rent_calculations.reject',
            'rent_manual_reviews.create',
            'rent_manual_reviews.approve',
            'rent_manual_reviews.reject',
            'rent_rule_sets.view',
            'rent_rule_sets.create',
            'rent_rule_sets.update',
            'rent_rule_sets.activate',
            'rent_rule_sets.archive',
            'rent_rule_sets.duplicate',
            'rent_rules.view',
            'rent_rules.create',
            'rent_rules.update',
            'accounts.view',
            'accounts.create',
            'accounts.detect_arrears',
            'arrears.view',
            'arrears.resolve',
            'default_notices.view',
            'default_notices.create',
            'default_notices.issue',
            'default_notices.cancel',
            'income_changes.view',
            'income_changes.approve',
            'income_changes.reject',
            'installments.view',
            'installments.issue',
            'installments.waive',
            'regularizations.view',
            'regularizations.create',
            'regularizations.approve',
            'regularizations.cancel',
            'rent_reviews.view',
            'rent_reviews.create',
            'rent_reviews.calculate',
            'rent_reviews.approve',
            'rent_reviews.reject',
            'rent_reviews.apply',
            'schedules.view',
            'schedules.generate',
        ],
        'maintenance_requests' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'review',
            'schedule',
            'start',
            'resolve',
            'close',
            'cancel',
        ],
        'maintenance' => [
            'categories.view',
            'categories.create',
            'categories.update',
            'categories.delete',
            'suppliers.view',
            'suppliers.create',
            'suppliers.update',
            'assignments.create',
            'assignments.cancel',
            'interventions.view',
            'interventions.create',
            'interventions.start',
            'interventions.complete',
            'interventions.cancel',
            'costs.view',
            'costs.create',
            'costs.approve',
            'costs.reject',
            'attachments.create',
            'attachments.download',
        ],
        'inspections' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'start',
            'complete',
            'close',
            'cancel',
            'validate',
            'items.create',
            'items.update',
            'attachments.create',
            'attachments.download',
            'templates.view',
            'templates.create',
            'templates.update',
            'reports.view',
            'reports.generate',
            'reports.validate',
            'reports.cancel',
            'reports.download',
        ],
        'notifications' => [
            'view',
            'create',
            'update',
            'delete',
            'publish',
            'export',
            'audit',
            'receipts.download',
            'mark_sent',
            'mark_failed',
        ],
        'communications' => [
            'view',
            'create',
            'cancel',
            'archive',
            'deliveries.resend',
            'deliveries.postal',
        ],
        'communication_variables' => ['view', 'create', 'update'],
        'notification_templates' => ['view', 'create', 'update', 'archive', 'preview'],
        'notification_template_versions' => ['view', 'create', 'approve', 'activate', 'archive'],
        'notification_event_rules' => ['view', 'create', 'update', 'activate', 'deactivate'],
        'notification_preferences' => ['view'],
        'internal_alerts' => ['view', 'detect', 'resolve', 'dismiss'],
        'reports' => [
            'view',
            'view_executive',
            'view_sensitive',
            'view_financial',
            'view_maintenance',
            'create',
            'update',
            'delete',
            'manage',
            'export',
            'export_sensitive',
            'export_financial',
            'export_nominal',
            'audit',
            'run',
        ],
        'report_definitions' => ['create', 'update', 'delete'],
        'dashboard_definitions' => ['view', 'create', 'update', 'delete'],
        'dashboard_widgets' => ['create', 'update', 'delete'],
        'indicator_definitions' => ['view', 'create', 'update'],
        'report_filter_presets' => ['view', 'create', 'update', 'delete'],
        'audit_logs' => ['view', 'export', 'audit'],
        'privacy' => ['view', 'create', 'update', 'delete', 'assign', 'approve', 'reject', 'export', 'audit'],
        'settings' => ['view', 'create', 'update', 'delete', 'activate', 'deactivate', 'audit'],
        'housing_units' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'simulator' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'visits' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'confirm',
            'complete',
            'cancel',
            'mark_no_show',
            'availabilities.view',
            'availabilities.create',
            'availabilities.update',
            'availabilities.delete',
            'availabilities.generate_slots',
            'slots.view',
            'slots.block',
            'slots.unblock',
        ],
        'agenda' => [
            'view',
        ],
        'support' => [
            'view',
            'create',
            'update',
            'delete',
            'approve',
            'reject',
            'export',
            'audit',
            'assign',
            'resolve',
            'message',
            'attachments.download',
        ],
        'contextual_faqs' => ['view', 'create', 'update', 'delete', 'publish', 'audit'],
        'candidate_experience' => ['view', 'create', 'update', 'export', 'audit'],
    ],

    'candidate_support' => [
        'minimum_reschedule_hours' => 24,
        'minimum_cancel_hours' => 24,
        'max_active_visits_per_application' => 3,
        'support_attachment_max_kb' => 10240,
    ],

    /*
    |--------------------------------------------------------------------------
    | Candidate experience runtime controls
    |--------------------------------------------------------------------------
    |
    | Legacy modules remain in the repository for historical compatibility,
    | but are disabled by default. Tenant support is available only after the
    | full post-award lifecycle has been completed.
    |
    */
    'candidate_experience_runtime' => [
        'notification_preferences' => env(
            'MVHAB_CANDIDATE_NOTIFICATION_PREFERENCES_ENABLED',
            false,
        ),
        'tenant_support' => env(
            'MVHAB_TENANT_SUPPORT_ENABLED',
            true,
        ),
    ],

    'procedural_notifications' => [
        'queue' => env('MVHAB_PROCEDURAL_EMAIL_QUEUE', 'communications'),
        'simulate' => env(
            'MVHAB_PROCEDURAL_EMAIL_SIMULATE',
            false,
        ),
        'tries' => 5,
        'retry_hours' => 12,
        'backoff' => [60, 300, 900, 3600],
    ],

    'roles' => [
        'administrator' => [
            'label' => 'Administrator',
            'permissions' => ['*'],
        ],
        'municipal_technician' => [
            'label' => 'Municipal technician',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'programs.view',
                'programs.create',
                'programs.update',
                'contests.view',
                'contests.create',
                'contests.update',
                'citizens.view',
                'citizens.create',
                'citizens.update',
                'citizens.export',
                'adhesion_registrations.view',
                'adhesion_registrations.create',
                'adhesion_registrations.update',
                'adhesion_registrations.approve',
                'adhesion_registrations.reject',
                'adhesion_registrations.export',
                'applications.view',
                'applications.create',
                'applications.update',
                'applications.submit',
                'applications.withdraw',
                'applications.approve',
                'applications.reject',
                'applications.export',
                'households.view',
                'households.create',
                'households.update',
                'households.export',
                'income_records.view',
                'income_records.create',
                'income_records.update',
                'income_records.export',
                'documents.view',
                'documents.create',
                'documents.update',
                'documents.replace',
                'documents.download',
                'documents.analyze',
                'documents.review_ai',
                'documents.generate',
                'documents.activate',
                'documents.archive',
                'documents.preview',
                'documents.issue',
                'documents.cancel',
                'documents.approve',
                'documents.reject',
                'eligibility.view',
                'eligibility.create',
                'eligibility.update',
                'eligibility.run',
                'eligibility.activate',
                'eligibility.deactivate',
                'eligibility.archive',
                'eligibility.duplicate',
                'eligibility.approve',
                'eligibility.reject',
                'administrative_processes.view',
                'administrative_processes.create',
                'administrative_processes.update',
                'administrative_processes.assign',
                'administrative_processes.decide',
                'administrative_processes.complete',
                'administrative_processes.cancel',
                'administrative_processes.issue',
                'administrative_processes.mark_overdue',
                'administrative_processes.approve',
                'administrative_processes.reject',
                'administrative_processes.publish',
                'administrative_processes.export',
                'administrative_decisions.view',
                'administrative_decisions.create',
                'administrative_decisions.approve',
                'administrative_decisions.cancel',
                'scoring.view',
                'scoring.create',
                'scoring.update',
                'scoring.review',
                'scoring.run',
                'scoring.lock',
                'scoring.cancel',
                'scoring.activate',
                'scoring.deactivate',
                'scoring.archive',
                'scoring.duplicate',
                'scoring.delete',
                'scoring.approve',
                'scoring.reject',
                'scoring.export',
                'public_lists.view',
                'public_lists.create',
                'public_lists.update',
                'public_lists.generate',
                'public_lists.review',
                'public_lists.approve',
                'public_lists.publish',
                'public_lists.archive',
                'public_lists.cancel',
                'public_lists.lock',
                'public_lists.open_complaint_period',
                'public_lists.close_complaint_period',
                'public_lists.export',
                'hearings.view',
                'hearings.create',
                'hearings.issue',
                'hearings.review',
                'hearings.accept',
                'hearings.reject',
                'hearings.close',
                'hearings.cancel',
                'complaints.view',
                'complaints.create',
                'complaints.update',
                'complaints.assign',
                'complaints.mark_received',
                'complaints.review',
                'complaints.request_information',
                'complaints.mark_overdue',
                'complaints.close',
                'complaints.decide',
                'complaints.approve',
                'complaints.reject',
                'complaints.cancel',
                'complaints.export',
                'allocations.view',
                'allocations.create',
                'allocations.update',
                'allocations.process_withdrawal',
                'allocations.export',
                'lotteries.view',
                'lotteries.create',
                'lotteries.update',
                'lotteries.run',
                'lotteries.validate',
                'lotteries.cancel',
                'lotteries.export',
                'lotteries.participants.load',
                'lotteries.participants.lock',
                'lotteries.convocations.generate',
                'lotteries.convocations.send',
                'lotteries.attendance.manage',
                'lotteries.winners.register',
                'lotteries.reports.generate',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'contracts.issue',
                'contracts.activate',
                'contracts.suspend',
                'contracts.terminate',
                'contracts.cancel',
                'contracts.sign',
                'contracts.templates.activate',
                'contracts.templates.archive',
                'contracts.templates.duplicate',
                'contracts.clauses.activate',
                'contracts.clauses.archive',
                'contracts.validations.create',
                'contracts.validations.approve',
                'contracts.validations.reject',
                'contracts.key_handovers.view',
                'contracts.key_handovers.schedule',
                'contracts.key_handovers.update',
                'contracts.key_handovers.complete',
                'contracts.key_handovers.cancel',
                'contracts.tenant_transitions.view',
                'contracts.tenant_transitions.run',
                'contracts.communications.view',
                'contracts.communications.create',
                'contracts.communications.message',
                'contracts.charge_runs.view',
                'contracts.charge_runs.run',
                'contracts.dashboard',
                'contracts.maintenance_reports.view',
                'payments.view',
                'payments.imports.view',
                'payments.receipts.view',
                'payments.invoices.view',
                'payments.tenant.view',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'finance.reject',
                'finance.export',
                'finance.deposits.view',
                'finance.rent_calculations.view',
                'finance.rent_calculations.calculate',
                'finance.rent_calculations.recalculate',
                'finance.rent_manual_reviews.create',
                'finance.rent_rule_sets.view',
                'finance.rent_rules.view',
                'finance.accounts.view',
                'finance.arrears.view',
                'finance.default_notices.view',
                'finance.income_changes.view',
                'finance.installments.view',
                'finance.regularizations.view',
                'finance.rent_reviews.view',
                'finance.rent_reviews.calculate',
                'finance.schedules.view',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'notifications.view',
                'notifications.create',
                'notifications.update',
                'notifications.mark_sent',
                'notifications.mark_failed',
                'communications.view',
                'communications.create',
                'communications.cancel',
                'communications.archive',
                'communications.deliveries.resend',
                'communications.deliveries.postal',
                'communication_variables.view',
                'notification_templates.view',
                'notification_templates.create',
                'notification_templates.update',
                'notification_templates.archive',
                'notification_templates.preview',
                'notification_template_versions.view',
                'notification_template_versions.create',
                'notification_template_versions.archive',
                'notification_event_rules.view',
                'notification_event_rules.create',
                'notification_event_rules.update',
                'notification_event_rules.activate',
                'notification_event_rules.deactivate',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'internal_alerts.resolve',
                'internal_alerts.dismiss',
                'reports.view',
                'reports.view_sensitive',
                'reports.view_maintenance',
                'reports.export',
                'reports.export_sensitive',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'housing_units.view',
                'housing_units.create',
                'housing_units.update',
                'simulator.view',
                'simulator.create',
                'simulator.update',
                'simulator.export',
                'visits.view',
                'visits.create',
                'visits.update',
                'visits.approve',
                'visits.reject',
                'visits.export',
                'support.view',
                'support.create',
                'support.update',
                'support.assign',
                'support.resolve',
                'support.message',
                'support.attachments.download',
                'support.approve',
                'support.reject',
                'support.export',
                'contextual_faqs.view',
                'contextual_faqs.create',
                'contextual_faqs.update',
                'contextual_faqs.publish',
                'candidate_experience.view',
                'candidate_experience.update',
                'candidate_experience.export',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.create',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.cancel',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'work_tasks.manage_sla',
                'agenda.view',
                'inspections.attachments.create',
                'inspections.cancel',
                'inspections.close',
                'inspections.complete',
                'inspections.items.create',
                'inspections.items.update',
                'inspections.reports.cancel',
                'inspections.reports.generate',
                'inspections.reports.view',
                'inspections.start',
                'inspections.templates.view',
                'maintenance.assignments.cancel',
                'maintenance.assignments.create',
                'maintenance.attachments.create',
                'maintenance.categories.view',
                'maintenance.costs.create',
                'maintenance.costs.view',
                'maintenance.interventions.cancel',
                'maintenance.interventions.complete',
                'maintenance.interventions.create',
                'maintenance.interventions.start',
                'maintenance.interventions.view',
                'maintenance.suppliers.view',
                'maintenance_requests.cancel',
                'maintenance_requests.close',
                'maintenance_requests.resolve',
                'maintenance_requests.review',
                'maintenance_requests.schedule',
                'maintenance_requests.start',
                'visits.availabilities.create',
                'visits.availabilities.generate_slots',
                'visits.availabilities.update',
                'visits.availabilities.view',
                'visits.cancel',
                'visits.complete',
                'visits.confirm',
                'visits.mark_no_show',
                'visits.slots.block',
                'visits.slots.unblock',
                'visits.slots.view',
            ],
        ],
        'jury' => [
            'label' => 'Jury',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'applications.view',
                'applications.approve',
                'applications.reject',
                'documents.view',
                'documents.download',
                'documents.preview',
                'eligibility.view',
                'eligibility.approve',
                'eligibility.reject',
                'administrative_processes.view',
                'administrative_processes.decide',
                'administrative_processes.approve',
                'administrative_processes.reject',
                'administrative_decisions.view',
                'administrative_decisions.create',
                'administrative_decisions.approve',
                'administrative_decisions.cancel',
                'scoring.view',
                'scoring.review',
                'scoring.run',
                'scoring.lock',
                'scoring.cancel',
                'scoring.approve',
                'scoring.reject',
                'public_lists.view',
                'public_lists.approve',
                'public_lists.reject',
                'public_lists.publish',
                'public_lists.lock',
                'hearings.view',
                'hearings.accept',
                'hearings.reject',
                'complaints.view',
                'complaints.approve',
                'complaints.reject',
                'complaints.cancel',
                'allocations.view',
                'allocations.approve',
                'allocations.reject',
                'lotteries.view',
                'lotteries.validate',
                'simulator.view',
                'visits.view',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
            ],
        ],
        'financial_manager' => [
            'label' => 'Financial manager',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'dashboard.export',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'contracts.approve',
                'contracts.export',
                'contracts.activate',
                'contracts.suspend',
                'contracts.validations.create',
                'contracts.validations.approve',
                'contracts.validations.reject',
                'contracts.communications.view',
                'contracts.communications.create',
                'contracts.communications.message',
                'contracts.charge_runs.view',
                'contracts.charge_runs.run',
                'contracts.dashboard',
                'payments.view',
                'payments.create',
                'payments.update',
                'payments.approve',
                'payments.reject',
                'payments.export',
                'payments.allocate',
                'payments.confirm',
                'payments.reverse',
                'payments.imports.view',
                'payments.imports.create',
                'payments.imports.process',
                'payments.receipts.view',
                'payments.receipts.generate',
                'payments.receipts.download',
                'payments.receipts.cancel',
                'payments.invoices.view',
                'payments.invoices.generate',
                'payments.tenant.view',
                'payments.tenant.create',
                'payments.tenant.confirm',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'finance.reject',
                'finance.export',
                'finance.deposits.view',
                'finance.deposits.request',
                'finance.deposits.mark_paid',
                'finance.deposits.waive',
                'finance.deposits.cancel',
                'finance.rent_calculations.view',
                'finance.rent_calculations.calculate',
                'finance.rent_calculations.recalculate',
                'finance.rent_calculations.approve',
                'finance.rent_calculations.reject',
                'finance.rent_manual_reviews.create',
                'finance.rent_manual_reviews.approve',
                'finance.rent_manual_reviews.reject',
                'finance.rent_rule_sets.view',
                'finance.rent_rule_sets.create',
                'finance.rent_rule_sets.update',
                'finance.rent_rule_sets.activate',
                'finance.rent_rule_sets.archive',
                'finance.rent_rule_sets.duplicate',
                'finance.rent_rules.view',
                'finance.rent_rules.create',
                'finance.rent_rules.update',
                'finance.accounts.view',
                'finance.accounts.create',
                'finance.accounts.detect_arrears',
                'finance.arrears.view',
                'finance.arrears.resolve',
                'finance.default_notices.view',
                'finance.default_notices.create',
                'finance.default_notices.issue',
                'finance.default_notices.cancel',
                'finance.income_changes.view',
                'finance.income_changes.approve',
                'finance.income_changes.reject',
                'finance.installments.view',
                'finance.installments.issue',
                'finance.installments.waive',
                'finance.regularizations.view',
                'finance.regularizations.create',
                'finance.regularizations.approve',
                'finance.regularizations.cancel',
                'finance.rent_reviews.view',
                'finance.rent_reviews.create',
                'finance.rent_reviews.calculate',
                'finance.rent_reviews.approve',
                'finance.rent_reviews.reject',
                'finance.rent_reviews.apply',
                'finance.schedules.view',
                'finance.schedules.generate',
                'reports.view',
                'reports.view_financial',
                'reports.export',
                'reports.export_financial',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'notifications.view',
                'notifications.create',
                'notifications.receipts.download',
                'communications.view',
                'communications.create',
                'notification_templates.view',
                'notification_template_versions.view',
                'notification_event_rules.view',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'simulator.view',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
                'maintenance.costs.approve',
                'maintenance.costs.reject',
                'maintenance.costs.view',
            ],
        ],
        'maintenance_manager' => [
            'label' => 'Maintenance manager',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'contracts.view',
                'contracts.communications.view',
                'contracts.communications.create',
                'contracts.communications.message',
                'contracts.dashboard',
                'contracts.maintenance_reports.view',
                'housing_units.view',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'maintenance_requests.approve',
                'maintenance_requests.reject',
                'maintenance_requests.export',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'inspections.approve',
                'inspections.reject',
                'inspections.export',
                'notifications.view',
                'notifications.create',
                'communications.view',
                'communications.create',
                'notification_templates.view',
                'notification_template_versions.view',
                'notification_event_rules.view',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'reports.view',
                'reports.view_maintenance',
                'reports.export',
                'reports.export_sensitive',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'simulator.view',
                'visits.view',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.cancel',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
                'inspections.attachments.create',
                'inspections.attachments.download',
                'inspections.cancel',
                'inspections.close',
                'inspections.complete',
                'inspections.items.create',
                'inspections.items.update',
                'inspections.reports.cancel',
                'inspections.reports.download',
                'inspections.reports.generate',
                'inspections.reports.validate',
                'inspections.reports.view',
                'inspections.start',
                'inspections.templates.create',
                'inspections.templates.update',
                'inspections.templates.view',
                'inspections.validate',
                'maintenance.assignments.cancel',
                'maintenance.assignments.create',
                'maintenance.attachments.create',
                'maintenance.attachments.download',
                'maintenance.categories.create',
                'maintenance.categories.delete',
                'maintenance.categories.update',
                'maintenance.categories.view',
                'maintenance.costs.create',
                'maintenance.costs.view',
                'maintenance.interventions.cancel',
                'maintenance.interventions.complete',
                'maintenance.interventions.create',
                'maintenance.interventions.start',
                'maintenance.interventions.view',
                'maintenance.suppliers.create',
                'maintenance.suppliers.update',
                'maintenance.suppliers.view',
                'maintenance_requests.cancel',
                'maintenance_requests.close',
                'maintenance_requests.resolve',
                'maintenance_requests.review',
                'maintenance_requests.schedule',
                'maintenance_requests.start',
            ],
        ],
        'legal_manager' => [
            'label' => 'Legal manager',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'applications.view',
                'documents.view',
                'documents.download',
                'documents.preview',
                'documents.audit',
                'administrative_processes.view',
                'administrative_processes.decide',
                'administrative_processes.approve',
                'administrative_processes.reject',
                'administrative_decisions.view',
                'administrative_decisions.create',
                'administrative_decisions.approve',
                'administrative_decisions.cancel',
                'public_lists.view',
                'public_lists.approve',
                'public_lists.reject',
                'hearings.view',
                'hearings.issue',
                'hearings.review',
                'hearings.accept',
                'hearings.reject',
                'hearings.close',
                'hearings.cancel',
                'complaints.view',
                'complaints.update',
                'complaints.assign',
                'complaints.mark_received',
                'complaints.review',
                'complaints.request_information',
                'complaints.mark_overdue',
                'complaints.close',
                'complaints.decide',
                'complaints.approve',
                'complaints.reject',
                'complaints.cancel',
                'complaints.audit',
                'allocations.view',
                'lotteries.view',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'contracts.approve',
                'contracts.reject',
                'contracts.audit',
                'contracts.issue',
                'contracts.activate',
                'contracts.suspend',
                'contracts.terminate',
                'contracts.cancel',
                'contracts.sign',
                'contracts.templates.activate',
                'contracts.templates.archive',
                'contracts.templates.duplicate',
                'contracts.clauses.activate',
                'contracts.clauses.archive',
                'contracts.validations.create',
                'contracts.validations.approve',
                'contracts.validations.reject',
                'contracts.communications.view',
                'contracts.communications.create',
                'contracts.communications.message',
                'contracts.dashboard',
                'reports.view',
                'reports.export',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'audit_logs.view',
                'access_audit.view',
                'privacy.view',
                'notifications.view',
                'notifications.create',
                'communications.view',
                'communications.create',
                'notification_templates.view',
                'notification_template_versions.view',
                'notification_event_rules.view',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.cancel',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
            ],
        ],
        'housing_manager' => [
            'label' => 'Housing manager',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'housing_units.view',
                'housing_units.create',
                'housing_units.update',
                'housing_units.export',
                'contests.view',
                'programs.view',
                'allocations.view',
                'allocations.create',
                'allocations.update',
                'allocations.approve',
                'allocations.reject',
                'allocations.process_withdrawal',
                'allocations.export',
                'lotteries.view',
                'lotteries.create',
                'lotteries.update',
                'lotteries.run',
                'lotteries.validate',
                'lotteries.cancel',
                'lotteries.export',
                'lotteries.participants.load',
                'lotteries.participants.lock',
                'lotteries.convocations.generate',
                'lotteries.convocations.send',
                'lotteries.attendance.manage',
                'lotteries.winners.register',
                'lotteries.reports.generate',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'contracts.issue',
                'contracts.activate',
                'contracts.suspend',
                'contracts.terminate',
                'contracts.cancel',
                'contracts.sign',
                'contracts.key_handovers.view',
                'contracts.key_handovers.schedule',
                'contracts.key_handovers.update',
                'contracts.key_handovers.complete',
                'contracts.key_handovers.cancel',
                'contracts.tenant_transitions.view',
                'contracts.tenant_transitions.run',
                'contracts.communications.view',
                'contracts.communications.create',
                'contracts.communications.message',
                'contracts.dashboard',
                'contracts.maintenance_reports.view',
                'maintenance_requests.view',
                'inspections.view',
                'visits.view',
                'visits.create',
                'visits.update',
                'reports.view',
                'reports.view_maintenance',
                'reports.export',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'notifications.view',
                'notifications.create',
                'communications.view',
                'communications.create',
                'notification_templates.view',
                'notification_template_versions.view',
                'notification_event_rules.view',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.cancel',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
                'visits.availabilities.create',
                'visits.availabilities.delete',
                'visits.availabilities.generate_slots',
                'visits.availabilities.update',
                'visits.availabilities.view',
                'visits.cancel',
                'visits.complete',
                'visits.confirm',
                'visits.mark_no_show',
                'visits.slots.block',
                'visits.slots.unblock',
                'visits.slots.view',
            ],
        ],
        'inspection_manager' => [
            'label' => 'Inspection manager',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'housing_units.view',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'inspections.approve',
                'inspections.reject',
                'inspections.export',
                'inspections.audit',
                'reports.view',
                'reports.view_maintenance',
                'reports.export',
                'reports.run',
                'dashboard_definitions.view',
                'indicator_definitions.view',
                'report_filter_presets.view',
                'report_filter_presets.create',
                'report_filter_presets.update',
                'report_filter_presets.delete',
                'notifications.view',
                'notifications.create',
                'communications.view',
                'communications.create',
                'notification_templates.view',
                'notification_template_versions.view',
                'notification_event_rules.view',
                'notification_preferences.view',
                'internal_alerts.view',
                'internal_alerts.detect',
                'support.view',
                'candidate_experience.view',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.reassign',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.cancel',
                'work_tasks.audit',
                'work_tasks.dashboard',
                'agenda.view',
                'inspections.attachments.create',
                'inspections.attachments.download',
                'inspections.cancel',
                'inspections.close',
                'inspections.complete',
                'inspections.items.create',
                'inspections.items.update',
                'inspections.reports.cancel',
                'inspections.reports.download',
                'inspections.reports.generate',
                'inspections.reports.validate',
                'inspections.reports.view',
                'inspections.start',
                'inspections.templates.create',
                'inspections.templates.update',
                'inspections.templates.view',
                'inspections.validate',
            ],
        ],
        'support_agent' => [
            'label' => 'Support agent',
            'permissions' => [
                'dashboard.view',
                'security.manage_own_mfa',
                'support.view',
                'support.create',
                'support.update',
                'support.assign',
                'support.resolve',
                'support.message',
                'support.attachments.download',
                'contextual_faqs.view',
                'contextual_faqs.create',
                'contextual_faqs.update',
                'candidate_experience.view',
                'candidate_experience.update',
                'notifications.view',
                'notifications.create',
                'communications.view',
                'communications.create',
                'notification_preferences.view',
                'simulator.view',
                'visits.view',
                'visits.update',
                'work_tasks.view',
                'work_tasks.view_team',
                'work_tasks.claim',
                'work_tasks.update_status',
                'work_tasks.complete',
                'work_tasks.dashboard',
                'agenda.view',
                'visits.availabilities.view',
                'visits.cancel',
                'visits.confirm',
                'visits.mark_no_show',
                'visits.slots.view',
            ],
        ],
        'candidate' => [
            'label' => 'Candidate',
            'permissions' => [
                'dashboard.view',
                'adhesion_registrations.view',
                'adhesion_registrations.create',
                'adhesion_registrations.update',
                'applications.view',
                'applications.create',
                'applications.update',
                'households.view',
                'households.create',
                'households.update',
                'households.delete',
                'income_records.view',
                'income_records.create',
                'income_records.update',
                'income_records.delete',
                'documents.view',
                'documents.create',
                'documents.update',
                'eligibility.view',
                'eligibility.create',
                'administrative_processes.view',
                'administrative_processes.create',
                'administrative_processes.update',
                'public_lists.view',
                'complaints.view',
                'complaints.create',
                'complaints.update',
                'allocations.view',
                'allocations.update',
                'contracts.view',
                'payments.view',
                'finance.view',
                'finance.create',
                'finance.update',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'inspections.view',
                'notifications.view',
                'privacy.view',
                'privacy.create',
                'privacy.update',
                'privacy.export',
                'simulator.view',
                'simulator.create',
                'simulator.update',
                'support.view',
                'support.create',
                'support.update',
                'contextual_faqs.view',
                'candidate_experience.view',
            ],
        ],
        'auditor' => [
            'label' => 'Auditor',
            'permissions' => [
                '*.view',
                '*.audit',
                'security.manage_own_mfa',
                'dashboard.export',
                'audit_logs.export',
                'security.view_access_logs',
                'security.audit_sensitive_access',
                'exports.audit',
                'exports.sensitive.audit',
                'rgpd.retention.view',
                'rgpd.anonymization.view',
                'contracts.key_handovers.view',
                'contracts.tenant_transitions.view',
                'contracts.communications.view',
                'contracts.charge_runs.view',
                'contracts.dashboard',
                'contracts.maintenance_reports.view',
                'payments.view',
                'payments.imports.view',
                'payments.receipts.view',
                'payments.invoices.view',
                'payments.tenant.view',
                'finance.deposits.view',
                'finance.rent_calculations.view',
                'finance.rent_rule_sets.view',
                'finance.rent_rules.view',
                'finance.accounts.view',
                'finance.arrears.view',
                'finance.default_notices.view',
                'finance.income_changes.view',
                'finance.installments.view',
                'finance.regularizations.view',
                'finance.rent_reviews.view',
                'finance.schedules.view',
                'inspections.reports.view',
                'inspections.templates.view',
                'maintenance.categories.view',
                'maintenance.costs.view',
                'maintenance.interventions.view',
                'maintenance.suppliers.view',
                'visits.availabilities.view',
                'visits.slots.view',
            ],
        ],
    ],
];
