<?php

return [
    'permissions' => [
        'dashboard' => ['view', 'export', 'audit'],
        'users' => ['view', 'create', 'update', 'delete', 'audit'],
        'municipalities' => ['view', 'create', 'update', 'delete', 'audit'],
        'programs' => ['view', 'create', 'update', 'delete', 'publish', 'audit'],
        'contests' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'publish', 'audit'],
        'citizens' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'adhesion_registrations' => ['view', 'create', 'update', 'approve', 'reject', 'export', 'audit'],
        'applications' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'households' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'income_records' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'documents' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'eligibility' => ['view', 'create', 'update', 'approve', 'reject', 'export', 'audit'],
        'administrative_processes' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'scoring' => ['view', 'create', 'update', 'approve', 'reject', 'export', 'audit'],
        'public_lists' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'publish', 'export', 'audit'],
        'complaints' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'allocations' => ['view', 'create', 'update', 'approve', 'reject', 'export', 'audit'],
        'contracts' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'payments' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'finance' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'maintenance_requests' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'inspections' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'notifications' => ['view', 'create', 'update', 'delete', 'publish', 'export', 'audit'],
        'reports' => [
            'view',
            'view_executive',
            'view_sensitive',
            'view_financial',
            'view_maintenance',
            'create',
            'update',
            'delete',
            'manage',
            'export',
            'export_sensitive',
            'export_financial',
            'export_nominal',
            'audit',
        ],
        'audit_logs' => ['view', 'export', 'audit'],
        'privacy' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'settings' => ['view', 'create', 'update', 'delete', 'audit'],
        'housing_units' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'simulator' => ['view', 'create', 'update', 'delete', 'export', 'audit'],
        'visits' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'support' => ['view', 'create', 'update', 'delete', 'approve', 'reject', 'export', 'audit'],
        'contextual_faqs' => ['view', 'create', 'update', 'delete', 'publish', 'audit'],
        'candidate_experience' => ['view', 'create', 'update', 'export', 'audit'],
    ],

    'candidate_support' => [
        'minimum_reschedule_hours' => 24,
        'minimum_cancel_hours' => 24,
        'max_active_visits_per_application' => 3,
        'support_attachment_max_kb' => 10240,
    ],

    'roles' => [
        'administrator' => [
            'label' => 'Administrator',
            'permissions' => ['*'],
        ],
        'municipal_technician' => [
            'label' => 'Municipal technician',
            'permissions' => [
                'dashboard.view',
                'programs.view',
                'programs.create',
                'programs.update',
                'contests.view',
                'contests.create',
                'contests.update',
                'citizens.view',
                'citizens.create',
                'citizens.update',
                'citizens.export',
                'adhesion_registrations.view',
                'adhesion_registrations.create',
                'adhesion_registrations.update',
                'adhesion_registrations.approve',
                'adhesion_registrations.reject',
                'adhesion_registrations.export',
                'applications.view',
                'applications.create',
                'applications.update',
                'applications.approve',
                'applications.reject',
                'applications.export',
                'households.view',
                'households.create',
                'households.update',
                'households.export',
                'income_records.view',
                'income_records.create',
                'income_records.update',
                'income_records.export',
                'documents.view',
                'documents.create',
                'documents.update',
                'documents.approve',
                'documents.reject',
                'eligibility.view',
                'eligibility.create',
                'eligibility.update',
                'eligibility.approve',
                'eligibility.reject',
                'administrative_processes.view',
                'administrative_processes.create',
                'administrative_processes.update',
                'administrative_processes.approve',
                'administrative_processes.reject',
                'administrative_processes.export',
                'scoring.view',
                'scoring.create',
                'scoring.update',
                'scoring.approve',
                'scoring.reject',
                'scoring.export',
                'public_lists.view',
                'public_lists.create',
                'public_lists.update',
                'public_lists.publish',
                'public_lists.export',
                'complaints.view',
                'complaints.create',
                'complaints.update',
                'complaints.approve',
                'complaints.reject',
                'complaints.export',
                'allocations.view',
                'allocations.create',
                'allocations.update',
                'allocations.export',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'payments.view',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'finance.reject',
                'finance.export',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'notifications.view',
                'notifications.create',
                'notifications.update',
                'reports.view',
                'reports.view_sensitive',
                'reports.view_maintenance',
                'reports.export',
                'reports.export_sensitive',
                'housing_units.view',
                'housing_units.create',
                'housing_units.update',
                'simulator.view',
                'simulator.create',
                'simulator.update',
                'simulator.export',
                'visits.view',
                'visits.create',
                'visits.update',
                'visits.approve',
                'visits.reject',
                'visits.export',
                'support.view',
                'support.create',
                'support.update',
                'support.approve',
                'support.reject',
                'support.export',
                'contextual_faqs.view',
                'contextual_faqs.create',
                'contextual_faqs.update',
                'contextual_faqs.publish',
                'candidate_experience.view',
                'candidate_experience.update',
                'candidate_experience.export',
            ],
        ],
        'jury' => [
            'label' => 'Jury',
            'permissions' => [
                'applications.view',
                'applications.approve',
                'applications.reject',
                'documents.view',
                'eligibility.view',
                'eligibility.approve',
                'eligibility.reject',
                'administrative_processes.view',
                'administrative_processes.approve',
                'administrative_processes.reject',
                'scoring.view',
                'scoring.approve',
                'scoring.reject',
                'public_lists.view',
                'public_lists.approve',
                'public_lists.reject',
                'public_lists.publish',
                'complaints.view',
                'complaints.approve',
                'complaints.reject',
                'allocations.view',
                'allocations.approve',
                'allocations.reject',
                'simulator.view',
                'visits.view',
                'support.view',
                'candidate_experience.view',
            ],
        ],
        'financial_manager' => [
            'label' => 'Financial manager',
            'permissions' => [
                'dashboard.view',
                'dashboard.export',
                'contracts.view',
                'contracts.create',
                'contracts.update',
                'contracts.approve',
                'contracts.export',
                'payments.view',
                'payments.create',
                'payments.update',
                'payments.approve',
                'payments.reject',
                'payments.export',
                'finance.view',
                'finance.create',
                'finance.update',
                'finance.approve',
                'finance.reject',
                'finance.export',
                'reports.view',
                'reports.view_financial',
                'reports.export',
                'reports.export_financial',
                'notifications.view',
                'notifications.create',
                'simulator.view',
                'support.view',
                'candidate_experience.view',
            ],
        ],
        'maintenance_manager' => [
            'label' => 'Maintenance manager',
            'permissions' => [
                'dashboard.view',
                'housing_units.view',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'maintenance_requests.approve',
                'maintenance_requests.reject',
                'maintenance_requests.export',
                'inspections.view',
                'inspections.create',
                'inspections.update',
                'inspections.approve',
                'inspections.reject',
                'inspections.export',
                'notifications.view',
                'notifications.create',
                'reports.view',
                'reports.view_maintenance',
                'reports.export',
                'reports.export_sensitive',
                'simulator.view',
                'visits.view',
                'support.view',
                'candidate_experience.view',
            ],
        ],
        'candidate' => [
            'label' => 'Candidate',
            'permissions' => [
                'dashboard.view',
                'adhesion_registrations.view',
                'adhesion_registrations.create',
                'adhesion_registrations.update',
                'applications.view',
                'applications.create',
                'applications.update',
                'households.view',
                'households.create',
                'households.update',
                'households.delete',
                'income_records.view',
                'income_records.create',
                'income_records.update',
                'income_records.delete',
                'documents.view',
                'documents.create',
                'documents.update',
                'eligibility.view',
                'eligibility.create',
                'administrative_processes.view',
                'administrative_processes.create',
                'administrative_processes.update',
                'public_lists.view',
                'complaints.view',
                'complaints.create',
                'complaints.update',
                'allocations.view',
                'allocations.update',
                'contracts.view',
                'payments.view',
                'finance.view',
                'finance.create',
                'finance.update',
                'maintenance_requests.view',
                'maintenance_requests.create',
                'maintenance_requests.update',
                'inspections.view',
                'notifications.view',
                'privacy.view',
                'privacy.create',
                'privacy.update',
                'privacy.export',
                'simulator.view',
                'simulator.create',
                'simulator.update',
                'visits.view',
                'visits.create',
                'visits.update',
                'support.view',
                'support.create',
                'support.update',
                'contextual_faqs.view',
                'candidate_experience.view',
            ],
        ],
        'auditor' => [
            'label' => 'Auditor',
            'permissions' => [
                '*.view',
                '*.audit',
                'dashboard.export',
                'reports.export',
                'audit_logs.export',
                'privacy.export',
            ],
        ],
    ],
];
