@csrf
@if(isset($report)) @method('PUT') @endif
<div class="grid gap-5 md:grid-cols-2">
    <div><x-input-label for="code" value="Código" /><x-text-input id="code" name="code" class="mt-1 block w-full" :value="old('code', $report->code ?? '')" required /></div>
    <div><x-input-label for="name" value="Nome" /><x-text-input id="name" name="name" class="mt-1 block w-full" :value="old('name', $report->name ?? '')" required /></div>
    <div class="md:col-span-2"><x-input-label for="description" value="Descrição" /><textarea id="description" name="description" class="mt-1 block w-full rounded-2xl border-ink-200">{{ old('description', $report->description ?? '') }}</textarea></div>
    <div><x-input-label for="report_type" value="Tipo" /><select id="report_type" name="report_type" class="mt-1 block w-full rounded-2xl border-ink-200">@foreach($types as $value => $label)<option value="{{ $value }}" @selected(old('report_type', isset($report) ? $report->report_type->value : '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="sensitivity_level" value="Sensibilidade" /><select id="sensitivity_level" name="sensitivity_level" class="mt-1 block w-full rounded-2xl border-ink-200">@foreach($sensitivities as $value => $label)<option value="{{ $value }}" @selected(old('sensitivity_level', isset($report) ? $report->sensitivity_level->value : '') === $value)>{{ $label }}</option>@endforeach</select></div>
    <div><x-input-label for="query_service" value="Serviço permitido" /><x-text-input id="query_service" name="query_service" class="mt-1 block w-full" :value="old('query_service', $report->query_service ?? 'App\\Services\\Reporting\\ReportQueryService')" required /></div>
    <div><x-input-label for="query_method" value="Método permitido" /><x-text-input id="query_method" name="query_method" class="mt-1 block w-full" :value="old('query_method', $report->query_method ?? '')" required /></div>
    <div><x-input-label for="required_permission" value="Permissão específica" /><x-text-input id="required_permission" name="required_permission" class="mt-1 block w-full" :value="old('required_permission', $report->required_permission ?? '')" /></div>
    <div class="flex items-center gap-5 pt-6"><label><input type="checkbox" name="requires_filters" value="1" @checked(old('requires_filters', $report->requires_filters ?? false))> Exigir filtros</label><label><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $report->is_active ?? true))> Ativo</label></div>
    <fieldset><legend class="text-sm font-medium text-ink-700">Formatos</legend>@foreach($formats as $value => $label)<label class="mr-4 mt-2 inline-flex gap-2"><input type="checkbox" name="available_formats[]" value="{{ $value }}" @checked(in_array($value, old('available_formats', $report->available_formats ?? ['html','csv']), true))>{{ $label }}</label>@endforeach</fieldset>
    <fieldset><legend class="text-sm font-medium text-ink-700">Âmbitos</legend>@foreach($scopes as $value => $label)<label class="mr-4 mt-2 inline-flex gap-2"><input type="checkbox" name="available_scopes[]" value="{{ $value }}" @checked(in_array($value, old('available_scopes', $report->available_scopes ?? ['aggregated']), true))>{{ $label }}</label>@endforeach</fieldset>
</div>
<div class="mt-6"><button class="mv-button-primary">Guardar</button></div>
