<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-civic-700">Área do candidato</p><h1 class="mt-1 text-2xl font-semibold text-ink-900">{{ $allocationOffer->offer_number }}</h1></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-5xl space-y-4 px-4 sm:px-6 lg:px-8"><x-flash-message />
        <div class="rounded-md border border-ink-100 bg-white p-6 text-sm"><dl class="grid gap-4 md:grid-cols-2"><div><dt class="text-ink-500">Concurso</dt><dd class="font-semibold">{{ $allocationOffer->allocation?->contest?->title }}</dd></div><div><dt class="text-ink-500">Habitação</dt><dd>{{ $allocationOffer->housingUnit?->code }}</dd></div><div><dt class="text-ink-500">Estado</dt><dd>{{ $allocationOffer->status->label() }}</dd></div><div><dt class="text-ink-500">Prazo de resposta</dt><dd>{{ $allocationOffer->response_deadline_at?->format('d/m/Y H:i') }}</dd></div></dl></div>
        <div class="grid gap-4 md:grid-cols-2">
            <form method="POST" action="{{ route('candidate.allocation-offers.accept', $allocationOffer) }}" class="rounded-md border border-civic-100 bg-white p-4">@csrf<label class="block text-sm font-medium text-ink-700">Observação<textarea name="candidate_response" class="mt-1 w-full rounded-md border-ink-200"></textarea></label><label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="confirm_acceptance" value="1"> Confirmo a aceitação da oferta</label><button class="mt-3 rounded-md bg-civic-700 px-4 py-2 text-sm font-semibold text-white">Aceitar</button></form>
            <form method="POST" action="{{ route('candidate.allocation-offers.refuse', $allocationOffer) }}" class="rounded-md border border-red-100 bg-white p-4">@csrf<label class="block text-sm font-medium text-ink-700">Motivo da recusa<textarea name="refusal_reason" class="mt-1 w-full rounded-md border-ink-200"></textarea></label><label class="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" name="confirm_refusal" value="1"> Confirmo a recusa da oferta</label><button class="mt-3 rounded-md border border-red-200 px-4 py-2 text-sm font-semibold text-red-700">Recusar</button></form>
        </div>
    </div></div>
</x-app-layout>
