<x-app-layout>
    <x-slot name="header"><div><p class="text-sm font-semibold text-mvhab-primary">Lista definitiva</p><h1 class="mt-1 text-2xl font-semibold text-ink-900">{{ $definitiveList->title }}</h1></div></x-slot>
    <div class="py-8"><div class="mx-auto max-w-7xl space-y-6 px-4 sm:px-6 lg:px-8">
        <div class="mv-surface p-6"><dl class="grid gap-4 md:grid-cols-4 text-sm"><div><dt class="text-ink-500">Número</dt><dd class="font-semibold">{{ $definitiveList->list_number }}</dd></div><div><dt class="text-ink-500">Origem</dt><dd>{{ $definitiveList->provisionalList?->list_number }}</dd></div><div><dt class="text-ink-500">Estado</dt><dd>{{ $definitiveList->status->label() }}</dd></div><div><dt class="text-ink-500">Alterações</dt><dd>{{ $definitiveList->changeLogs->count() }}</dd></div></dl></div>
        <div class="flex flex-wrap gap-2"><form method="POST" action="{{ route('backoffice.lists.definitive.review', $definitiveList) }}">@csrf<x-secondary-button>Rever</x-secondary-button></form><form method="POST" action="{{ route('backoffice.lists.definitive.approve', $definitiveList) }}">@csrf<x-secondary-button>Aprovar</x-secondary-button></form><form method="POST" action="{{ route('backoffice.lists.definitive.publish', $definitiveList) }}">@csrf<x-primary-button>Publicar</x-primary-button></form><form method="POST" action="{{ route('backoffice.lists.definitive.lock', $definitiveList) }}">@csrf<x-secondary-button>Bloquear</x-secondary-button></form></div>
        <div class="mv-surface overflow-hidden"><table class="min-w-full divide-y divide-ink-100 text-sm"><thead class="bg-ink-50 text-left text-xs font-semibold uppercase text-ink-500"><tr><th class="px-4 py-3">Posição</th><th class="px-4 py-3">Identificador</th><th class="px-4 py-3">Estado</th><th class="px-4 py-3">Alteração</th></tr></thead><tbody class="divide-y divide-ink-100">@foreach($definitiveList->entries as $entry)<tr><td class="px-4 py-3">{{ $entry->rank_position }}</td><td class="px-4 py-3 font-semibold">{{ $entry->public_identifier }}</td><td class="px-4 py-3">{{ $entry->status->label() }}</td><td class="px-4 py-3">{{ $entry->change_reason }}</td></tr>@endforeach</tbody></table></div>
    </div></div>
</x-app-layout>

